dist: trusty

language: python
python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.7-dev"
before_install:
  - pip install -U pip setuptools
install:
  - make install
script:
  - make test
  - make test_docs
  - make lint
notifications:
  email: false
